version: '3.7'

services:

  bot:
    image: alyetama/discord-backup-bot:latest
    #build: .
    restart: always
    command: python app/bot.py --use-all-services
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POLR_SERVER=${POLR_SERVER}
      - POLR_KEY=${POLR_KEY}

  minio:
    image: minio/minio
    restart: always
    ports:
      - ${MINIO_SERVER_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    command: server /data --console-address ":9001"
    volumes:
      - ./buckets:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}

  polr:
    image: ajanvier/polr
    ports:
        - "${POLR_PORT:-8080}:8080"
    environment:
      - APP_NAME=${APP_NAME:-polr}
      - APP_PROTOCOL="${APP_PROTOCOL:-https://}"
      - APP_ADDRESS=${APP_ADDRESS}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SETTING_SHORTEN_PERMISSION=true
      - SETTING_PSEUDORANDOM_ENDING=true
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-polr}
      - DB_USERNAME=${DB_USERNAME:-polr}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "${DB_PORT:-3306}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE:-polr}
      - MYSQL_USER=${DB_USERNAME:-polr}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/lib/mysql
      - ./mysql-data:/var/lib/mysql
