version: '3.7'

services:

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - ./buckets:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}

  polr:
    image: ajanvier/polr
    ports:
        - "8080:8080"
    environment:
      - APP_NAME=polr
      - APP_PROTOCOL="https://"
      - APP_ADDRESS=${POLR_APP_ADDRESS}
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${POLR_ADMIN_PASSWORD}
      - SETTING_SHORTEN_PERMISSION=true
      - SETTING_PSEUDORANDOM_ENDING=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=polr
      - DB_USERNAME=polr
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${POLR_DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
